export const USER_SIGNUP = {
  REQUEST: "USER_SIGNUP_REQUEST",
  SUCCESS: "USER_SIGNUP_SUCCESS",
  FAIL: "USER_SIGNUP_FAIL",
};

export const USER_LOGIN = {
  REQUEST: "USER_LOGIN_REQUEST",
  SUCCESS: "USER_LOGIN_SUCCESS",
  FAIL: "USER_LOGIN_FAIL",
};
