export const IMAGE_UPLOAD = {
  REQUEST: "IMAGE_UPLOAD_REQUEST",
  SUCCESS: "IMAGE_UPLOAD_SUCCESS",
  NULL: "IMAGE_UPLOAD_NULL",
};

export const CREATE_POST = {
  REQUEST: "CREATE_POST_REQUEST",
  SUCCESS: "CREATE_POST_SUCCESS",
  FAIL: "CREATE_POST_FAIL",
  NULL: "CREATE_POST_NULL",
};

export const ALL_POST = {
  REQUEST: "ALL_POST_REQUEST",
  SUCCESS: "ALL_POST_SUCCESS",
};

export const MY_POST = {
  REQUEST: "MY_POST_REQUEST",
  SUCCESS: "MY_POST_SUCCESS",
};
